### ISSUE TITLE
discrete priors with ABC-SMC

### ISSUE THREAD

**Issue by mauricelanghinrichs** [marcjwilliams1/ApproxBayes.jl#51] opened 2020-03-25 11:09 UTC
Hi,

thanks a lot for this package, I really enjoy using it! However, I came into a situation now where I would like to use discrete prior distributions. I noted that the ABCRejection algorithm still works, while the ABCSMC algorithm (which I usually tend to use) gets stuck in preparing the run.

minimal working example:
```
using ApproxBayes
using Distributions
using Random

Random.seed!(1)
p1 = 100.0
p2 = 10.0
targetdata = rand(Normal(p1, p2), 1000)

function normaldist(params, constants, targetdata)
  simdata = rand(Normal(params...), 1000)
  ApproxBayes.ksdist(simdata, targetdata), 1
end

setup = ABCSMC(normaldist, # ABCSMC() or ABCRejection()
  2,
  0.1,
  Prior([DiscreteUniform(0.0, 200.0), Uniform(0.0, 50.0)]), # discrete prior for p1
  )

smc = runabc(setup, targetdata, verbose = true, progress = true)

mean(smc.parameters, dims=1)
median(smc.parameters, dims=1)
```

output:
```
##################################################
Use ABC rejection to get first population
Preparing to run in serial on 1 processor
Running ABC SMC... 

Preparing to run in serial on 1 processor

```

Is there a way to make ABC-SMC work with discrete priors like this? I would be extremely glad for any help!

Best

**Comment by marcjwilliams1** [comment] 2020-05-26 09:37
Hi @mauricelanghinrichs, sorry this issue passed me by till now, is this still a problem for you? 

I think the problem is how the limits for the priors are constructed between population runs in the SMC, should be able to change this. Let me know and I can try and take a look.

**Comment by francescoalemanno** [comment] 2020-05-26 15:28
@marcjwilliams1 thank you for the beautiful package, i think that also the perturbation kernels must be fixed in order to make discrete jumps in case the prior is discrete, as values with 0 prior probability must not be in the posterior

**Comment by marcjwilliams1** [comment] 2020-05-27 12:08
thanks, yes you're right that a custom perturbation kernel would also be needed.

**Comment by mauricelanghinrichs** [comment] 2020-05-28 11:15
thanks for your replies!

> Hi @mauricelanghinrichs, sorry this issue passed me by till now, is this still a problem for you?

yes, I'm still working with discrete priors and also will need them in the longer foreseeable future :) so if there is a fix for this, it would be awesome!

currently I'm using the ABCRejection version of your package, this did not throw errors with discrete priors. But I'm not so into the algorithmic side at the moment, is this guaranteed to give the right sampling at all?

**Comment by marcjwilliams1** [comment] 2020-05-29 15:44
@mauricelanghinrichs I haven't tried this but I think something like the below is what you'll need. Give it a go and if you encounter any errors that aren't obvious to you let me know.

```
perturbation_function(prevparameter, scale) = rand(DiscreteUniform(prevparameter - scale, prevparameter + scale))

pdf_function(newparticle, prevparticle, scales, i) = pdf(DiscreteUniform(prevparticle.params[i] - scales[i], prevparticle.params[i] + scales[i]), newparticle.params[i])
function calculate_kernel_parameters(particles)
  #calculate the range of parameter values (ie the scale) to use for the
  #perturbation kernel
  parameters = hcat(map(x -> x.params, particles)...)'
  scales = ((maximum(parameters, dims = 1) -
                  minimum(parameters, dims = 1)) ./ 2.0)[:]
  return scales
end

discreteuniformkernel = Kernel(
    perturbation_function,
    pdf_function,
    calculate_kernel_parameters
)

setup = ABCSMC(normaldist, # ABCSMC() or ABCRejection()
  2,
  0.1,
  Prior([DiscreteUniform(0.0, 200.0), Uniform(0.0, 50.0)]), # discrete prior for p1,
  kernel = discreteuniformkernel
  )
```

In terms of the accuracy of the algorithms, as eps -> 0 then the ABC algorithms will converge to the statistically accurate posterior distribution. This is true for both the rejection and the SMC algorithm. Of course, the SMC is more efficient so can get to the same eps faster, but for the same eps the results should be the same.

**Comment by marcjwilliams1** [comment] 2020-05-29 15:46
FYI there is also this package which has some additional features and might take Discrete priors out of the box - https://github.com/tanhevg/GpABC.jl

**Comment by francescoalemanno** [comment] 2020-05-29 17:35
> @mauricelanghinrichs I haven't tried this but I think something like the below is what you'll need. Give it a go and if you encounter any errors that aren't obvious to you let me know.

i think this is not entirely sufficient as most models with discrete parameters also have continuous parameters, and a single discrete pert. kernel will not work on continuous parameters.

perhaps at the moment it is best to use a continuous prior and round the samples inside the model, this is not theoretically correct but works in practice

**Comment by marcjwilliams1** [comment] 2020-05-29 18:21
Yes that was going to be my other suggestion. I agree that it probably works well even if it's not theoretically correct. To check you could run the both SMC and Rejection for the same epsilon and check if there are any differences, I would expect any differences to be minimal.

**Comment by mauricelanghinrichs** [comment] 2020-05-29 19:45
> i think this is not entirely sufficient as most models with discrete parameters also have continuous parameters, and a single discrete pert. kernel will not work on continuous parameters.

yeah, that's the situation I typically need.

> perhaps at the moment it is best to use a continuous prior and round the samples inside the model, this is not theoretically correct but works in practice

> To check you could run the both SMC and Rejection for the same epsilon and check if there are any differences, I would expect any differences to be minimal.

thanks both of you! I will try that soon.

**Closed as completed** 2023-07-12 13:52 UTC
